### ISSUE TITLE
Supporting jemalloc installation

### ISSUE THREAD

**Issue by omarsotillo** [asdf-vm/asdf-ruby#117]
Hello! 🤖 Is `asdf` supporting any flag for installing any ruby version with jemalloc? like the following rvm command: `rvm reinstall 2.7.0-dev -C —with-jemalloc`?

**Comment by BliZZ4RD** [comment]
@omarsotillo since asdf-ruby uses ruby-build, you can pass options via [RUBY_CONFIGURE_OPTS](https://github.com/asdf-vm/asdf-ruby/blob/master/bin/install#L29)
`RUBY_CONFIGURE_OPTS=--with-jemalloc asdf install ruby 2.6.3`

It appears that library support is now in `CONFIG['MAINLIBS']` in 2.6.x, previously it was in `CONFIG['LIBS']`

```
# ruby -e "p RbConfig::CONFIG['MAINLIBS']"
"-lpthread -ljemalloc -lgmp -ldl -lobjc"
```

**Comment by jaydorsey** [comment]
Just a note, the environment variable name appears to have changed to `RUBY_BUILD_OPTS` (per where that file links now)

This works with the most recent version of asdf/asdf-ruby (just tried it today)

    RUBY_BUILD_OPTS=--with-jemalloc asdf install ruby 2.6.3

The comment about MAINLIBS is very helpful because I've seen old documentation that pointed to LIBS and I wouldn't have realized that changed

**Comment by omarsotillo** [comment]
Thanks! @jaydorsey @BliZZ4RD

**Comment by DragosDumitrache** [comment]
Hey folks, if I follow these instructions, when looking at the ruby libs to double check, jemalloc doesn't show up

**Comment by mhenrixon** [comment]
```
RUBY_CONFIGURE_OPTS="--with-readline-dir=/opt/homebrew/opt/readline --with-jemalloc=/opt/homebrew/opt/jemalloc --enable-yjit --with-zlib-dir=/opt/homebrew/opt/zlib --with-libyaml-dir=/opt/homebrew/opt/libyaml --with-gdbm-dir=/opt/homebrew/opt/gdbm" asdf install ruby 3.2.2
```

Crashes with: `configure: error: jemalloc requested but not found.`

While `ruby-install` works with the same: 

```
RUBY_CONFIGURE_OPTS="--with-readline-dir=/opt/homebrew/opt/readline --with-jemalloc=/opt/homebrew/opt/jemalloc --enable-yjit --with-zlib-dir=/opt/homebrew/opt/zlib --with-libyaml-dir=/opt/homebrew/opt/libyaml --with-gdbm-dir=/opt/homebrew/opt/gdbm" ruby-install 3.2.2
```

It seems odd that asdf (ruby-build) won't work with the same configuration options.

**Comment by ashwinv11** [comment]
I had to run this to successfully install Ruby 3.2.2 with asdf and jemalloc on my Apple Silicon Mac (M1 Pro running MacOS Monterey 12.6)

https://github.com/rbenv/ruby-build/discussions/1843#discussioncomment-1871673

```bash
export HOMEBREW_PREFIX=$(brew --prefix)
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/jemalloc/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/jemalloc/include"
RUBY_CONFIGURE_OPTS="--with-jemalloc=$(brew --prefix jemalloc)" asdf install ruby 3.2.2
```

Then to confirm Ruby is using jemalloc as expected:

```
irb -rrbconfig
irb(main):002:0> RbConfig::CONFIG['MAINLIBS']
=> "-ljemalloc -lgmp -ldl -lobjc -lpthread "
```

Note the `-ljemalloc` at the end. Hope that helps!

**Comment by joshuapinter** [comment]
@ashwinv11 Thank you for this. I added this to my`.zshrc` and it worked like a charm. Brilliant.
