### ISSUE TITLE
update ruby-build to most-recent version to handle ruby 2.7

### ISSUE THREAD

**Issue by hurricup** [asdf-vm/asdf-ruby#120]
Why not just use actual version all the time?

**Comment by sriedel** [comment]
Since asdf-ruby uses rbenvs build-ruby for the version information, a quickfix would be to replace the value of RUBY_BUILD_VERSION in $HOME/.asdf/plugins/ruby/lib/utils.sh.

Since the github API is rather easy to use, the programmatic way is two curl calls:

    tag_name=$(curl --silent  -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/rbenv/ruby-build/releases/latest | fgrep tag_name | awk -F\…" '{print $4 }')
    RUBY_BUILD_VERSION=$(curl --silent -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/rbenv/ruby-build/git/refs/tags/v20190615 | fgrep sha | awk …-F\" '{print $4}')

I haven't found where asdf abstracts from available shell commands or which shell commands in general are expected to be present for asdf to run, since the above already has issues (awk vs gawk), as the use of jq would be a lot cleaner.

If the asdf team is ok with the above approach, I can see if I can clobber together a PR, although this opens a can of works (error handling, caching of results so you don't issue api requests to github everytime you do a list-all etc).

**Comment by Stratus3D** [comment]
We always use a tag or commit hash to ensure every user of asdf-ruby gets a known version of ruby-build. There are no guarantees that the API of ruby-build will never change, so by installing a specific version of it we ensure that a new tag will not break existing asdf-ruby installations.

**Comment by Stratus3D** [comment]
The reason we used a commit hash instead of a tag was because there were some recent changes to ruby-build that users wanted, and the ruby-build maintainers don't always tag releases after making changes.

See https://github.com/asdf-vm/asdf-ruby/issues/108
