### ISSUE TITLE
Performance with asdf multiple gems?

### ISSUE THREAD

**Issue by niksfirefly** [asdf-vm/asdf-ruby#137]
I come from RVM world and I wonder is there any performance problem when I use multiple gems for many projects with same ruby version.
Rvm gives gemsets where we separate gems for every project.
Asdf get every gem from same dir so we have big list of gems.
Is there any performance problems with this approach?

**Comment by Stratus3D** [comment]
@niksfirefly I am not aware of any, but I have not investigated this. The only overhead asdf adds is version lookup that happens when a command is executed (e.g. when `rails` is executed asdf must figure out where the current ruby version is located, and execute the binary in the gem that provides it).

If you are concerned about this, I'd suggest looking around for any general information on Ruby performance problems with many gems.

**Comment by Stratus3D** [comment]
I'm going to close this as I do not think there is anything in asdf-ruby that needs to be changed.
