### ISSUE TITLE
2.7.2 not in list?

### ISSUE THREAD

**Issue by neenjaw** [asdf-vm/asdf-ruby#188]
Hello,

I am using asdf to mange my ruby version, and have been waiting for [2.7.2](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/) to show in the installable list (via `asdf list-all ruby`).  Is 2.7.2 not available via asdf? or is this an error happening on my end?

**Comment by mylanconnolly** [comment]
I'd verify that you have the latest version of this plugin and then try to install again.

```shell
asdf plugin update ruby
asdf install ruby 2.7.2
```

**Comment by neenjaw** [comment]
That seems to have fixed it.  Sorry for creating an issue over something so trivial.  I also use asdf for elixir versioning and it seems to pull dynamically so I had never encountered this.  Thanks for your time and advice!

**Comment by mylanconnolly** [comment]
Glad to hear it!

I'm not a contributor, just a user like you, but I figured it out on my own a while back and figured I'd pay it forward. This plugin uses `ruby-build` behind the scenes, which I think needs to get updated in order to pull the new Ruby versions, which I think accounts for the difference in behavior.
