### ISSUE TITLE
env RUBY_BUILD_MIRROR_URL not work

### ISSUE THREAD

**Issue by defp** [asdf-vm/asdf-ruby#272]
output 

```
➜  ~ RUBY_BUILD_MIRROR_URL=https://cache.ruby-china.com asdf install ruby 3.1.2
Downloading ruby-3.1.2.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.2.tar.gz
```

```
➜  ~ asdf --version
v0.10.0-77fd510

```

**Comment by Stratus3D** [comment]
Interesting. What if you use a separate export instead like this?

```
$ export RUBY_BUILD_MIRROR_URL=https://cache.ruby-china.com 
$ asdf install ruby 3.1.2
```

**Comment by defp** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/612381/169202195-dea82618-ede6-40be-a64b-4c0f4d233b6b.png">

**Comment by Stratus3D** [comment]
I tested this and experienced the same issue. It's not clear to me what the cause is, but I don't see anything in asdf-ruby that would contribute to this.

@eregon do you have any idea what is going on here?

If we don't hear back from @eregon I'd suggest either opening an issue on the ruby-build issue tracker. A quick scan of the ruby-build code does reveal there is a scenario where this variable appears to be ignored - when no 256 shas can be computed - see https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build#L1440-L1442.

**Comment by eregon** [comment]
Please report an issue to ruby-build, I didn't write that logic.

**Comment by Stratus3D** [comment]
Sadly it does not appear to be fixed in ruby-build yet @glyh . Please comment on that ruby-build issue if it's causing a problem for you.
