### ISSUE TITLE
better way determined ruby-build version

### ISSUE THREAD

**Issue by marocchino** [asdf-vm/asdf-ruby#319]
It seems inefficient to receive a PR every time there is an update of Ruby.
I want to refer to other plugins and automatically refer to the latest version.

**Comment by kriansa** [comment]
You can `export ASDF_RUBY_BUILD_VERSION=master` so that it automatically picks up the latest `ruby-build`. Does that help?

**Comment by marocchino** [comment]
There are two problems.
- Master is not a stable latest release.
- I can do that, but it's hard to ask other team members to add settings. To recommend replacing rbenv with asdf-ruby, it should be updated at least at the same timing as rbenv and not slower than rbenv.

**Comment by kriansa** [comment]
Master is stable, at least for `ruby-build`, you can take a look at the commits from the past 6 months, they all have been tagged as a release, so you can pretty much rely on master as the `latest` release.

As for team-wise orientation, I feel your pain. However, that is hardly a repetitive or frequent ask. I understand the reason why you started this issue was because the maintainer took a while longer to approve a PR to update ruby-build and thus Ruby 3.1.3. 

That happens, life happens and no project is immune to that, even `ruby-build` itself uses a similar method for updating the build defs on their side. Regardless though, that event is so rare that this is honestly the first time I ever face it, and I've been using `asdf` for over a year.

It would be very frustrating if this had no workaround, which is definitely not the case: if you need desperately to install the latest Ruby as soon as it comes out - assuming it is already available on `ruby-build` - you can easily export an env variable on your terminal and install it. That is enough IMHO.

On the other hand, to find that out I had to come to this repository and look for the issues, which is not a common route most users would take.

My take on this issue would be to add a helpful message whenever a user tries to install a ruby version not available on `ruby-build`, guiding them to use the latest by exporting the env variable or linking the readme.

**Comment by marocchino** [comment]
Thank you for your reply.

>  I understand the reason why you started this issue was because the maintainer took a while longer to approve a PR to update ruby-build and thus Ruby 3.1.3.

That's the trigger, but asdf-nodejs or asdf-elixir don't need this kind of merge process, so I thought there was no reason to do this only in asdf-ruby.

> My take on this issue would be to add a helpful message whenever a user tries to install a ruby version not available on ruby-build, guiding them to use the latest by exporting the env variable or linking the readme.

The biggest reason is that I thought it would be difficult to find a solution with just the explanation below.
```sh
$ asdf install ruby 3.1.3
ruby-build: definition not found: 3.1.3
```

BTW, I think this description of Read Me should also be corrected.

> Running asdf plugin-update ruby will update asdf-ruby and ensure the latest versions of ruby are available to install. By default asdf-ruby uses the latest release of ruby-build.

But since this is open source, I respect the maintainer's decision. Feel free to close this issue.

**Comment by Stratus3D** [comment]
Hi @marocchino thanks for opening this issue and the associated PR! And sorry for the late review here!

> That's the trigger, but asdf-nodejs or asdf-elixir don't need this kind of merge process, so I thought there was no reason to do this only in asdf-ruby.

asdf-elixir doesn't use another tool underneath, so there is no dependency that needs to be updated. asdf-erlang does use a tool called kerl for building Erlang, but it doesn't need to be updated that often - it pulls in the list of available versions dynamically. I can't speak to asdf-nodejs as I'm not that familiar with the project.

Ideally I'd like all plugins to behave like asdf-elixir (not depend on another build tool) or like asdf-erlang (rely on a build tool that pulls in a list of available versions dynamically). ruby-build isn't great because it has to be updated before it lists new Ruby versions. So unlike Erlang's kerl, we can't distinguish between ruby-build code changes and new Ruby versions.

Additionally, if this plugin always pulls in the latest version of ruby-build, it may cause problems when asdf plugins are eventually versioned. For example, rolling back to an old version of asdf-ruby wouldn't change anything because it'd still be using the latest version of ruby-build underneath. We want things to be as deterministic as possible here.

>  That is acceptable option. because The biggest reason is that I thought it would be difficult to find a solution with just the explanation below.

https://github.com/asdf-vm/asdf-ruby/pull/322 was recently merged for this. I'm going to close this issue but please do reply if I've missed anything here.
