### ISSUE TITLE
Automatic reshim after gem installing/uninstalling 

### ISSUE THREAD

**Issue by AlexWayfer** [asdf-vm/asdf-ruby#63]
Hello!

It's weird that I should exec `asdf reshim ruby` after any gem installation and uninstallation.

So, I've ran `bundle`, which installed needed dependencies, but I can't exec `rspec`, for example.

Please.

**Comment by domcorvasce** [comment]
Actually, asdf-ruby is doing it for us.
I'm running Ubuntu 16.04 and I'm able to use a gem right after I've installed it.
Try to update asdf-ruby.

**Comment by AlexWayfer** [comment]
I'm tired to reinstall all rubies and gems, so let's wait for #61.

**Comment by mattbrictson-babylon** [comment]
> So, I've ran bundle, which installed needed dependencies, but I can't exec rspec

Agreed, I am seeing the same thing.

I have found that:

* asdf-ruby _does_ automatically reshim if you install a gem via `gem install ...` 
* it does _not_ automatically reshim if you install gems via `bundle install`

Looking at the code, it appears this is because asdf-ruby has only partially implemented the solution that rbenv uses. You can see that in asdf-ruby, it hooks into gem install:

https://github.com/asdf-vm/asdf-ruby/blob/b94f282df2e263c4f07c892dcdc195f9bfcda2b6/rubygems-plugin/rubygems_plugin.rb#L3-L11

But it does not hook into bundler like rbenv does here:

https://github.com/rbenv/rbenv/blob/1c772d5ff21bbee52e0c6cdf128c5cffaf8feea8/rbenv.d/exec/gem-rehash/rubygems_plugin.rb#L14-L35

**Comment by mattbrictson** [comment]
> So, I've ran bundle, which installed needed dependencies, but I can't exec rspec

Agreed, I am seeing the same thing.

I have found that:

* asdf-ruby _does_ automatically reshim if you install a gem via `gem install ...` 
* it does _not_ automatically reshim if you install gems via `bundle install`

Looking at the code, it appears this is because asdf-ruby has only partially implemented the solution that rbenv uses. You can see that in asdf-ruby, it hooks into gem install:

https://github.com/asdf-vm/asdf-ruby/blob/b94f282df2e263c4f07c892dcdc195f9bfcda2b6/rubygems-plugin/rubygems_plugin.rb#L3-L11

But it does not hook into bundler like rbenv does here:

https://github.com/rbenv/rbenv/blob/1c772d5ff21bbee52e0c6cdf128c5cffaf8feea8/rbenv.d/exec/gem-rehash/rubygems_plugin.rb#L14-L35

**Comment by AlexWayfer** [comment]
@mattbrictson nice catch! Thank you.

**Comment by hurricup** [comment]
Any updates on `bundle install` handling?
