### ISSUE TITLE
bundle fails to install ffi

### ISSUE THREAD

**Issue by rlipscombe** [asdf-vm/asdf-ruby#92]
I've got a `Gemfile` containing just `fpm`. I've got `asdf local ruby 2.4.5`:

```
$ gem environment gemdir
/home/roger/.asdf/installs/ruby/2.4.5/lib/ruby/gems/2.4.0
$ gem install bundler
$ asdf reshim ruby        # <- just in case
$ VISUAL=echo gem open bundler
/home/roger/.asdf/installs/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.0.1
```

...looks correct. But...

```
$ bundle
...
Installing ffi 1.10.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20190129-27080-1pk9ascffi-1.10.0/gems/ffi-1.10.0/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20190129-27080-1i6fp9p.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20190129-27080-1pk9ascffi-1.10.0/gems/ffi-1.10.0 for inspection.
Results logged to /tmp/bundler20190129-27080-1pk9ascffi-1.10.0/extensions/x86_64-linux/2.3.0/ffi-1.10.0/gem_make.out
```

It's using `/usr/bin/ruby2.3`, rather than the asdf-managed one. I don't have `/usr/lib/ruby/include/`.

The `Results logged to` lines are wrong -- there are no bundler files in `/tmp`.

Later in the output, it says:

```
An error occurred while installing ffi (1.10.0), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.10.0'` succeeds before bundling.
```

OK...

```
$ gem install ffi -v '1.10.0'
Building native extensions.  This could take a while...
Successfully installed ffi-1.10.0
Parsing documentation for ffi-1.10.0
Done installing documentation for ffi after 2 seconds
1 gem installed

$ VISUAL=echo gem open ffi
/home/roger/.asdf/installs/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/ffi-1.10.0
```

But that still doesn't fix anything. `bundle` still fails.

**Comment by SeanSith** [comment]
Installs fine on macOS 10.14.3 following your steps. What platform are you having issues with?

**Comment by rlipscombe** [comment]
Ubuntu 16.04.

**Comment by SeanSith** [comment]
My environment: 
  - Ubuntu 16.04 provided via Virtualbox, Vagrant, and the bento/ubuntu-16.04 box. 
  - Installed asdf-vm per instructions in the project README.
  - Installed asdf-ruby per instructions in its project README. 
  - `apt install ruby2.3` to potentially get the `/usr/bin/ruby2.3` you mentioned above (which would otherwise be unnecessary).

Followed your steps as listed above and received no error. 

Please check your `$PATH` variable to ensure that `~/.asdf/shims` is listed before `/usr/bin` (this comes as part of the asdf-vm installation process where you're encouraged to update `~/.bashrc` with the autocompletion and environment scripts and restart your shell). Also a `which bundle` should be pointing at the `~/.asdf/shims` directory rather than /usr/bin.

It's likely that you're either missing the environment script or that you're somehow injecting the `shims` directory later than /usr/bin, which would then cause your environment to prefer the commands in /usr/bin over those available in asdf-vm.

**Comment by Stratus3D** [comment]
@rlipscombe I ran into that exact issue maybe 3 weeks ago. Sadly I don't recall the solution. It took me a while to figure it out, but if I remember correctly it wasn't a bug and it was fairly straightforward to correct.

**Comment by rlipscombe** [comment]
Rather than use asdf, I've since decided to use direnv + various chopped up bits (python-build from pyenv, and ruby-build). I had the same problem initially with my frankensolution -- I think it came down to installing the bundle gem, rather than the bundler gem.

I added some stuff to my direnv-stuff to automatically install the bundler gem if it detects a Gemfile, which prevents me from making that mistake again.

Happy to close this, since I can no longer reproduce it, and the above might be sufficient hint for anyone else in the future.
