### ISSUE TITLE
ruby-build: definition not found: 2.6.1

### ISSUE THREAD

**Issue by gobijan** [asdf-vm/asdf-ruby#96]
Hi I don't know why the asdf-ruby version of ruby-build has an old list of released rubies.
My dedicated version of ruby-build has 2.6.1 already available. How do I get asdf-ruby to install 2.6.1?

**Comment by chills42** [comment]
It looks like there is an open pull request https://github.com/asdf-vm/asdf-ruby/pull/93 to address this issue.

**Comment by gobijan** [comment]
OK I see... A bit unfortunate that ruby-build bundled is used even though a newer ruby-build system is available.

**Comment by bxt** [comment]
I got the same error with a different ruby version, and I found my ruby plugin for asdf was just outdated. Since I installed asdf via brew and also update it there, I did not know you have to update those independently from asdf. So I did the following:

```
asdf plugin-update ruby
```

This way I could then run e.g. to confirm that the latest ruby versions are there

```
asdf list-all ruby
```

 or even to install the newly appeared version something like this:

```
asdf install ruby 2.6.3
```

Not related to this issue in particular, but this comes up when you Google the error message, so maybe this helps someone.

**Comment by wilsonsilva** [comment]
Perhaps the plugin should suggest this command upon failure?
